@echo Checking if it can compile...
"C:\Program Files (x86)\Mono-2.6.7\bin\gmcs.bat" -warn:0 -out:MyBot.exe "C:\Users\Mira\Documents\Visual Studio 2010\Projects\DTU\Google AI Challenge\Ants\Ants.Qua\ImprovedFindFood\MyBot\*.cs"
pause